version: '3.8'

services:
  # Serviço do Banco de Dados
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: easy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Serviço da sua API Phoenix
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db  # Espera o banco iniciar antes de tentar subir
    volumes:
      - .:/app # Sincroniza sua pasta local com o container (Hot Reload funciona!)
    environment:
      DB_HOSTNAME: db
      DB_PASSWORD: postgres

volumes:
  postgres_data: